-- Location: supabase/migrations/20260106223000_add_clips_table.sql
-- Schema Analysis: Existing tables: projects, user_profiles
-- Integration Type: Addition - Multi-scene video clip tracking
-- Dependencies: projects (existing)

-- ENUM for clip generation status
CREATE TYPE public.clip_status AS ENUM ('pending', 'generating', 'completed', 'failed');

-- Create clips table for storing individual video scene clips
CREATE TABLE public.clips (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    scene_index INTEGER NOT NULL,
    video_url TEXT,
    status public.clip_status DEFAULT 'pending'::public.clip_status NOT NULL,
    prompt_used TEXT NOT NULL,
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    CONSTRAINT clips_project_scene_unique UNIQUE(project_id, scene_index)
);

-- Indexes for clips table
CREATE INDEX idx_clips_project_id ON public.clips(project_id);
CREATE INDEX idx_clips_status ON public.clips(status);
CREATE INDEX idx_clips_scene_index ON public.clips(scene_index);

-- Enable RLS for clips table
ALTER TABLE public.clips ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can only access clips for their own projects
CREATE POLICY "users_manage_own_project_clips"
ON public.clips
FOR ALL
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.projects p
        WHERE p.id = clips.project_id AND p.user_id = auth.uid()
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.projects p
        WHERE p.id = clips.project_id AND p.user_id = auth.uid()
    )
);

-- Trigger to update updated_at timestamp
CREATE TRIGGER update_clips_updated_at
BEFORE UPDATE ON public.clips
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Comment on table
COMMENT ON TABLE public.clips IS 'Individual video scene clips generated by Pika Labs for scripture projects';